export type Perfume = {
  id: string
  name: string
  brand: string
  gender: "masc" | "fem" | "unisex"
  brandType: "clasica" | "arabe"
  tags: string[]
}

/**
 * Vocabulario de tags (deben coincidir con los tags de las opciones en questions.ts):
 * Familias: dulce, gourmand, vainilla, amaderada, especiada, frutal, tropical,
 *           fresca, aromatica, cuero, oud, floral, citrica, acuatica, cafe, azucar
 * Estación: primavera, verano, otono, invierno
 * Ocasión: trabajo, casual, cita, noche, fiesta
 * Dulzor: nada-dulce, ligero-dulce, dulce, muy-dulce
 * Proyección: discreta, moderada, alta, bestia
 * Vibe: elegante, calido, seductor, lujo, versatil, misterio, cercano, fresco, aventurero, original, dominante
 * Único: popular, conocido, diferente, raro
 */

export const perfumes: Perfume[] = [
  // ---------- MASCULINOS CLÁSICOS ----------
  {
    id: "fierce",
    name: "Fierce",
    brand: "Abercrombie & Fitch",
    gender: "masc",
    brandType: "clasica",
    tags: ["aromatica", "fresca", "amaderada", "casual", "trabajo", "primavera", "otono", "nada-dulce", "moderada", "fresco", "versatil", "popular", "cercano"],
  },
  {
    id: "adg",
    name: "Acqua di Gio Profumo",
    brand: "Giorgio Armani",
    gender: "masc",
    brandType: "clasica",
    tags: ["acuatica", "fresca", "amaderada", "trabajo", "casual", "verano", "primavera", "nada-dulce", "moderada", "elegante", "fresco", "versatil", "popular", "conocido"],
  },
  {
    id: "armani-code",
    name: "Armani Code Profumo",
    brand: "Giorgio Armani",
    gender: "masc",
    brandType: "clasica",
    tags: ["especiada", "amaderada", "dulce", "cita", "noche", "otono", "invierno", "dulce", "alta", "seductor", "elegante", "calido", "conocido"],
  },
  {
    id: "swy-intensely",
    name: "Stronger With You Intensely",
    brand: "Giorgio Armani",
    gender: "masc",
    brandType: "clasica",
    tags: ["dulce", "gourmand", "vainilla", "especiada", "cita", "noche", "invierno", "otono", "muy-dulce", "alta", "seductor", "calido", "popular"],
  },
  {
    id: "sauvage-elixir",
    name: "Sauvage Elixir",
    brand: "Dior",
    gender: "masc",
    brandType: "clasica",
    tags: ["especiada", "amaderada", "aromatica", "noche", "cita", "invierno", "otono", "ligero-dulce", "bestia", "seductor", "elegante", "dominante", "popular"],
  },
  {
    id: "sauvage",
    name: "Sauvage",
    brand: "Dior",
    gender: "masc",
    brandType: "clasica",
    tags: ["fresca", "aromatica", "especiada", "trabajo", "casual", "primavera", "verano", "nada-dulce", "alta", "fresco", "versatil", "popular"],
  },
  {
    id: "dior-homme-intense",
    name: "Dior Homme Intense",
    brand: "Dior",
    gender: "masc",
    brandType: "clasica",
    tags: ["amaderada", "floral", "elegante", "cita", "noche", "invierno", "otono", "ligero-dulce", "alta", "elegante", "lujo", "seductor", "conocido"],
  },
  {
    id: "fahrenheit",
    name: "Fahrenheit",
    brand: "Dior",
    gender: "masc",
    brandType: "clasica",
    tags: ["amaderada", "cuero", "especiada", "otono", "invierno", "casual", "noche", "nada-dulce", "alta", "original", "misterio", "conocido"],
  },
  {
    id: "terre-hermes",
    name: "Terre d'Hermès",
    brand: "Hermès",
    gender: "masc",
    brandType: "clasica",
    tags: ["amaderada", "citrica", "especiada", "trabajo", "casual", "otono", "primavera", "nada-dulce", "moderada", "elegante", "versatil", "conocido"],
  },
  {
    id: "le-male-elixir",
    name: "Le Male Elixir",
    brand: "Jean Paul Gaultier",
    gender: "masc",
    brandType: "clasica",
    tags: ["gourmand", "vainilla", "dulce", "amaderada", "noche", "cita", "invierno", "muy-dulce", "bestia", "seductor", "calido", "conocido"],
  },
  {
    id: "ultra-male",
    name: "Ultra Male",
    brand: "Jean Paul Gaultier",
    gender: "masc",
    brandType: "clasica",
    tags: ["dulce", "frutal", "gourmand", "fiesta", "noche", "cita", "primavera", "muy-dulce", "alta", "seductor", "aventurero", "popular"],
  },
  {
    id: "invictus",
    name: "Invictus",
    brand: "Paco Rabanne",
    gender: "masc",
    brandType: "clasica",
    tags: ["acuatica", "fresca", "frutal", "casual", "fiesta", "verano", "primavera", "ligero-dulce", "alta", "fresco", "aventurero", "popular"],
  },
  {
    id: "one-million",
    name: "One Million",
    brand: "Paco Rabanne",
    gender: "masc",
    brandType: "clasica",
    tags: ["especiada", "amaderada", "dulce", "cuero", "fiesta", "noche", "cita", "invierno", "dulce", "alta", "lujo", "seductor", "dominante", "popular"],
  },
  {
    id: "invictus-victory",
    name: "Invictus Victory",
    brand: "Paco Rabanne",
    gender: "masc",
    brandType: "clasica",
    tags: ["especiada", "amaderada", "fresca", "noche", "fiesta", "invierno", "ligero-dulce", "bestia", "lujo", "dominante", "conocido"],
  },
  {
    id: "bleu-chanel",
    name: "Bleu de Chanel",
    brand: "Chanel",
    gender: "masc",
    brandType: "clasica",
    tags: ["amaderada", "aromatica", "citrica", "trabajo", "cita", "casual", "otono", "primavera", "nada-dulce", "moderada", "elegante", "versatil", "lujo", "popular"],
  },
  {
    id: "y-elixir",
    name: "Y Elixir",
    brand: "Yves Saint Laurent",
    gender: "masc",
    brandType: "clasica",
    tags: ["amaderada", "aromatica", "especiada", "noche", "cita", "otono", "invierno", "ligero-dulce", "alta", "elegante", "seductor", "lujo", "conocido"],
  },
  {
    id: "noir-homme",
    name: "Nuit de L'Homme",
    brand: "Yves Saint Laurent",
    gender: "masc",
    brandType: "clasica",
    tags: ["especiada", "amaderada", "dulce", "cita", "noche", "otono", "invierno", "dulce", "moderada", "seductor", "elegante", "conocido"],
  },
  {
    id: "eros",
    name: "Eros",
    brand: "Versace",
    gender: "masc",
    brandType: "clasica",
    tags: ["dulce", "aromatica", "fresca", "fiesta", "noche", "cita", "primavera", "invierno", "dulce", "alta", "seductor", "aventurero", "popular"],
  },
  {
    id: "dylan-blue",
    name: "Dylan Blue",
    brand: "Versace",
    gender: "masc",
    brandType: "clasica",
    tags: ["acuatica", "fresca", "amaderada", "trabajo", "casual", "verano", "primavera", "nada-dulce", "moderada", "fresco", "versatil", "conocido"],
  },
  {
    id: "the-one-dg",
    name: "The One",
    brand: "Dolce & Gabbana",
    gender: "masc",
    brandType: "clasica",
    tags: ["especiada", "amaderada", "dulce", "cafe", "trabajo", "cita", "otono", "invierno", "dulce", "moderada", "elegante", "calido", "conocido"],
  },
  {
    id: "kbydg",
    name: "K by Dolce & Gabbana",
    brand: "Dolce & Gabbana",
    gender: "masc",
    brandType: "clasica",
    tags: ["citrica", "amaderada", "especiada", "casual", "trabajo", "verano", "primavera", "nada-dulce", "moderada", "fresco", "versatil", "conocido"],
  },
  {
    id: "boss-bottled",
    name: "Boss Bottled Night",
    brand: "Hugo Boss",
    gender: "masc",
    brandType: "clasica",
    tags: ["amaderada", "aromatica", "especiada", "trabajo", "cita", "otono", "invierno", "ligero-dulce", "moderada", "elegante", "versatil", "popular"],
  },
  {
    id: "legend-mb",
    name: "Legend",
    brand: "Mont Blanc",
    gender: "masc",
    brandType: "clasica",
    tags: ["aromatica", "fresca", "amaderada", "trabajo", "casual", "primavera", "otono", "nada-dulce", "moderada", "elegante", "versatil", "cercano", "popular"],
  },
  {
    id: "gentleman-society",
    name: "Gentleman Society",
    brand: "Givenchy",
    gender: "masc",
    brandType: "clasica",
    tags: ["floral", "amaderada", "fresca", "trabajo", "cita", "primavera", "otono", "ligero-dulce", "alta", "elegante", "versatil", "conocido"],
  },
  {
    id: "spicebomb",
    name: "Spicebomb",
    brand: "Viktor & Rolf",
    gender: "masc",
    brandType: "clasica",
    tags: ["especiada", "amaderada", "cuero", "noche", "invierno", "cita", "ligero-dulce", "alta", "calido", "dominante", "conocido"],
  },
  {
    id: "aventus",
    name: "Aventus",
    brand: "Creed",
    gender: "masc",
    brandType: "clasica",
    tags: ["frutal", "amaderada", "ahumado", "lujo", "trabajo", "cita", "noche", "primavera", "otono", "ligero-dulce", "alta", "lujo", "elegante", "dominante", "conocido"],
  },
  {
    id: "ombre-leather",
    name: "Ombré Leather",
    brand: "Tom Ford",
    gender: "unisex",
    brandType: "clasica",
    tags: ["cuero", "amaderada", "floral", "noche", "cita", "otono", "invierno", "nada-dulce", "alta", "lujo", "misterio", "diferente"],
  },
  {
    id: "tobacco-vanille",
    name: "Tobacco Vanille",
    brand: "Tom Ford",
    gender: "unisex",
    brandType: "clasica",
    tags: ["gourmand", "vainilla", "especiada", "dulce", "noche", "invierno", "muy-dulce", "bestia", "lujo", "calido", "misterio", "diferente"],
  },
  {
    id: "oud-wood",
    name: "Oud Wood",
    brand: "Tom Ford",
    gender: "unisex",
    brandType: "clasica",
    tags: ["oud", "amaderada", "especiada", "noche", "cita", "otono", "invierno", "nada-dulce", "moderada", "lujo", "elegante", "misterio", "diferente"],
  },
  {
    id: "naxos",
    name: "Naxos",
    brand: "Xerjoff",
    gender: "unisex",
    brandType: "clasica",
    tags: ["gourmand", "vainilla", "tabaco", "miel", "dulce", "noche", "invierno", "otono", "muy-dulce", "alta", "lujo", "calido", "raro"],
  },

  // ---------- MASCULINOS / UNISEX ÁRABES ----------
  {
    id: "9pm",
    name: "9PM",
    brand: "Afnan",
    gender: "masc",
    brandType: "arabe",
    tags: ["dulce", "gourmand", "vainilla", "especiada", "noche", "cita", "invierno", "otono", "dulce", "alta", "seductor", "calido", "diferente"],
  },
  {
    id: "asad",
    name: "Asad",
    brand: "Lattafa",
    gender: "masc",
    brandType: "arabe",
    tags: ["amaderada", "especiada", "cafe", "dulce", "noche", "cita", "invierno", "dulce", "bestia", "dominante", "calido", "diferente"],
  },
  {
    id: "khamrah",
    name: "Khamrah",
    brand: "Lattafa",
    gender: "unisex",
    brandType: "arabe",
    tags: ["gourmand", "especiada", "dulce", "vainilla", "canela", "noche", "invierno", "otono", "muy-dulce", "bestia", "calido", "lujo", "diferente"],
  },
  {
    id: "khamrah-qahwa",
    name: "Khamrah Qahwa",
    brand: "Lattafa",
    gender: "unisex",
    brandType: "arabe",
    tags: ["gourmand", "cafe", "especiada", "dulce", "noche", "invierno", "muy-dulce", "alta", "calido", "misterio", "diferente"],
  },
  {
    id: "badee-glory",
    name: "Bade'e Al Oud for Glory",
    brand: "Lattafa",
    gender: "unisex",
    brandType: "arabe",
    tags: ["oud", "amaderada", "especiada", "frutal", "noche", "otono", "invierno", "ligero-dulce", "bestia", "lujo", "misterio", "diferente"],
  },
  {
    id: "asad-bourbon",
    name: "Asad Bourbon",
    brand: "Lattafa",
    gender: "masc",
    brandType: "arabe",
    tags: ["gourmand", "cafe", "dulce", "amaderada", "noche", "invierno", "muy-dulce", "alta", "calido", "seductor", "diferente"],
  },
  {
    id: "maahir-black",
    name: "Maahir Black",
    brand: "Lattafa",
    gender: "unisex",
    brandType: "arabe",
    tags: ["frutal", "amaderada", "especiada", "cita", "noche", "otono", "primavera", "ligero-dulce", "alta", "elegante", "lujo", "diferente"],
  },
  {
    id: "qaed-fursan",
    name: "Qaed Al Fursan",
    brand: "Lattafa",
    gender: "masc",
    brandType: "arabe",
    tags: ["frutal", "dulce", "amaderada", "noche", "fiesta", "cita", "otono", "dulce", "alta", "aventurero", "seductor", "diferente"],
  },
  {
    id: "cdn-original",
    name: "Club de Nuit Intense",
    brand: "Armaf",
    gender: "masc",
    brandType: "arabe",
    tags: ["frutal", "amaderada", "ahumado", "trabajo", "cita", "noche", "primavera", "otono", "ligero-dulce", "bestia", "elegante", "dominante", "diferente"],
  },
  {
    id: "cdn-untold",
    name: "Club de Nuit Untold Yum Yum",
    brand: "Armaf",
    gender: "unisex",
    brandType: "arabe",
    tags: ["dulce", "gourmand", "frutal", "fiesta", "noche", "cita", "muy-dulce", "alta", "seductor", "original", "diferente"],
  },
  {
    id: "hawas",
    name: "Hawas",
    brand: "Rasasi",
    gender: "masc",
    brandType: "arabe",
    tags: ["acuatica", "fresca", "frutal", "amaderada", "casual", "trabajo", "verano", "primavera", "ligero-dulce", "alta", "fresco", "versatil", "diferente"],
  },
  {
    id: "amber-oud-gold",
    name: "Amber Oud Gold",
    brand: "Al Haramain",
    gender: "unisex",
    brandType: "arabe",
    tags: ["frutal", "amaderada", "oud", "dulce", "noche", "cita", "otono", "invierno", "dulce", "alta", "lujo", "misterio", "diferente"],
  },
  {
    id: "oud-greatness",
    name: "Oud for Greatness",
    brand: "Initio",
    gender: "unisex",
    brandType: "arabe",
    tags: ["oud", "especiada", "amaderada", "noche", "otono", "invierno", "ligero-dulce", "bestia", "lujo", "misterio", "raro"],
  },
  {
    id: "amber-rouge",
    name: "Amber Rouge",
    brand: "Orientica",
    gender: "unisex",
    brandType: "arabe",
    tags: ["amaderada", "oud", "frutal", "dulce", "noche", "cita", "otono", "invierno", "dulce", "alta", "lujo", "seductor", "diferente"],
  },
  {
    id: "teriaq",
    name: "Teriaq",
    brand: "Lattafa",
    gender: "unisex",
    brandType: "arabe",
    tags: ["gourmand", "vainilla", "especiada", "dulce", "noche", "invierno", "otono", "dulce", "alta", "calido", "lujo", "diferente"],
  },
  {
    id: "tiramisu-coco",
    name: "Tiramisu Coco",
    brand: "Lattafa",
    gender: "unisex",
    brandType: "arabe",
    tags: ["gourmand", "cafe", "vainilla", "dulce", "noche", "invierno", "muy-dulce", "moderada", "calido", "cercano", "diferente"],
  },

  // ---------- NICHO / UNISEX ----------
  {
    id: "br540",
    name: "Baccarat Rouge 540",
    brand: "Maison Francis Kurkdjian",
    gender: "unisex",
    brandType: "clasica",
    tags: ["gourmand", "amaderada", "floral", "azafran", "dulce", "noche", "cita", "otono", "invierno", "dulce", "bestia", "lujo", "misterio", "raro"],
  },
  {
    id: "santal33",
    name: "Santal 33",
    brand: "Le Labo",
    gender: "unisex",
    brandType: "clasica",
    tags: ["amaderada", "cuero", "especiada", "casual", "trabajo", "otono", "invierno", "nada-dulce", "moderada", "elegante", "original", "raro"],
  },
  {
    id: "bianco-latte",
    name: "Bianco Latte",
    brand: "Giardini di Toscana",
    gender: "unisex",
    brandType: "clasica",
    tags: ["gourmand", "vainilla", "dulce", "leche", "casual", "cita", "invierno", "otono", "muy-dulce", "moderada", "cercano", "calido", "diferente"],
  },
  {
    id: "delina",
    name: "Delina",
    brand: "Parfums de Marly",
    gender: "fem",
    brandType: "clasica",
    tags: ["floral", "frutal", "dulce", "cita", "noche", "primavera", "otono", "dulce", "alta", "elegante", "seductor", "lujo", "raro"],
  },
  {
    id: "layton",
    name: "Layton Exclusif",
    brand: "Parfums de Marly",
    gender: "unisex",
    brandType: "clasica",
    tags: ["gourmand", "especiada", "vainilla", "amaderada", "noche", "cita", "invierno", "otono", "dulce", "bestia", "lujo", "elegante", "raro"],
  },
  {
    id: "lost-cherry",
    name: "Lost Cherry",
    brand: "Tom Ford",
    gender: "unisex",
    brandType: "clasica",
    tags: ["gourmand", "frutal", "dulce", "almendra", "noche", "cita", "invierno", "otono", "muy-dulce", "alta", "seductor", "lujo", "raro"],
  },
  {
    id: "black-orchid",
    name: "Black Orchid",
    brand: "Tom Ford",
    gender: "unisex",
    brandType: "clasica",
    tags: ["floral", "amaderada", "especiada", "dulce", "noche", "cita", "invierno", "otono", "dulce", "alta", "misterio", "lujo", "seductor", "diferente"],
  },
  {
    id: "intense-cafe",
    name: "Intense Café",
    brand: "Montale",
    gender: "unisex",
    brandType: "clasica",
    tags: ["gourmand", "cafe", "floral", "dulce", "noche", "invierno", "otono", "dulce", "alta", "calido", "seductor", "diferente"],
  },
  {
    id: "erba-pura",
    name: "Erba Pura",
    brand: "Xerjoff",
    gender: "unisex",
    brandType: "clasica",
    tags: ["frutal", "dulce", "citrica", "fiesta", "casual", "verano", "primavera", "dulce", "alta", "aventurero", "versatil", "raro"],
  },

  // ---------- FEMENINOS CLÁSICOS ----------
  {
    id: "good-girl",
    name: "Good Girl",
    brand: "Carolina Herrera",
    gender: "fem",
    brandType: "clasica",
    tags: ["floral", "gourmand", "amaderada", "dulce", "noche", "cita", "fiesta", "invierno", "otono", "dulce", "alta", "seductor", "elegante", "dominante", "popular"],
  },
  {
    id: "212-vip-rose",
    name: "212 VIP Rosé",
    brand: "Carolina Herrera",
    gender: "fem",
    brandType: "clasica",
    tags: ["frutal", "floral", "dulce", "fiesta", "cita", "primavera", "verano", "dulce", "alta", "aventurero", "seductor", "popular"],
  },
  {
    id: "ch-good-girl-blush",
    name: "Good Girl Blush",
    brand: "Carolina Herrera",
    gender: "fem",
    brandType: "clasica",
    tags: ["floral", "frutal", "dulce", "casual", "cita", "primavera", "verano", "dulce", "moderada", "cercano", "versatil", "conocido"],
  },
  {
    id: "la-vie-est-belle",
    name: "La Vie est Belle",
    brand: "Lancôme",
    gender: "fem",
    brandType: "clasica",
    tags: ["gourmand", "floral", "dulce", "vainilla", "cita", "noche", "otono", "invierno", "muy-dulce", "alta", "seductor", "calido", "popular"],
  },
  {
    id: "idole",
    name: "Idôle",
    brand: "Lancôme",
    gender: "fem",
    brandType: "clasica",
    tags: ["floral", "fresca", "almizcle", "trabajo", "casual", "primavera", "verano", "ligero-dulce", "moderada", "elegante", "versatil", "conocido"],
  },
  {
    id: "black-opium",
    name: "Black Opium",
    brand: "Yves Saint Laurent",
    gender: "fem",
    brandType: "clasica",
    tags: ["gourmand", "cafe", "vainilla", "dulce", "noche", "fiesta", "cita", "otono", "invierno", "muy-dulce", "alta", "seductor", "misterio", "popular"],
  },
  {
    id: "libre",
    name: "Libre",
    brand: "Yves Saint Laurent",
    gender: "fem",
    brandType: "clasica",
    tags: ["floral", "aromatica", "vainilla", "cita", "noche", "otono", "primavera", "ligero-dulce", "alta", "elegante", "seductor", "conocido"],
  },
  {
    id: "coco-mademoiselle",
    name: "Coco Mademoiselle",
    brand: "Chanel",
    gender: "fem",
    brandType: "clasica",
    tags: ["floral", "citrica", "amaderada", "trabajo", "cita", "otono", "primavera", "ligero-dulce", "alta", "elegante", "lujo", "popular"],
  },
  {
    id: "chance",
    name: "Chance",
    brand: "Chanel",
    gender: "fem",
    brandType: "clasica",
    tags: ["floral", "fresca", "citrica", "trabajo", "casual", "primavera", "verano", "ligero-dulce", "moderada", "elegante", "versatil", "lujo", "conocido"],
  },
  {
    id: "jadore",
    name: "J'Adore",
    brand: "Dior",
    gender: "fem",
    brandType: "clasica",
    tags: ["floral", "frutal", "elegante", "trabajo", "cita", "primavera", "otono", "ligero-dulce", "alta", "elegante", "lujo", "popular"],
  },
  {
    id: "miss-dior",
    name: "Miss Dior",
    brand: "Dior",
    gender: "fem",
    brandType: "clasica",
    tags: ["floral", "frutal", "dulce", "cita", "primavera", "verano", "dulce", "moderada", "elegante", "cercano", "conocido"],
  },
  {
    id: "hypnotic-poison",
    name: "Hypnotic Poison",
    brand: "Dior",
    gender: "fem",
    brandType: "clasica",
    tags: ["gourmand", "vainilla", "almendra", "especiada", "dulce", "noche", "invierno", "otono", "muy-dulce", "alta", "seductor", "misterio", "conocido"],
  },
  {
    id: "my-way",
    name: "My Way",
    brand: "Giorgio Armani",
    gender: "fem",
    brandType: "clasica",
    tags: ["floral", "fresca", "almizcle", "trabajo", "cita", "primavera", "otono", "ligero-dulce", "moderada", "elegante", "versatil", "conocido"],
  },
  {
    id: "si-armani",
    name: "Sì",
    brand: "Giorgio Armani",
    gender: "fem",
    brandType: "clasica",
    tags: ["floral", "frutal", "amaderada", "dulce", "cita", "noche", "otono", "primavera", "dulce", "alta", "elegante", "seductor", "conocido"],
  },
  {
    id: "scandal",
    name: "Scandal",
    brand: "Jean Paul Gaultier",
    gender: "fem",
    brandType: "clasica",
    tags: ["gourmand", "floral", "miel", "dulce", "fiesta", "noche", "cita", "otono", "muy-dulce", "alta", "seductor", "aventurero", "conocido"],
  },
  {
    id: "fame",
    name: "Fame",
    brand: "Paco Rabanne",
    gender: "fem",
    brandType: "clasica",
    tags: ["floral", "frutal", "amaderada", "fiesta", "cita", "primavera", "verano", "ligero-dulce", "alta", "original", "aventurero", "conocido"],
  },
  {
    id: "lady-million",
    name: "Lady Million",
    brand: "Paco Rabanne",
    gender: "fem",
    brandType: "clasica",
    tags: ["floral", "frutal", "dulce", "fiesta", "noche", "cita", "primavera", "dulce", "alta", "lujo", "seductor", "popular"],
  },
  {
    id: "olympea",
    name: "Olympéa",
    brand: "Paco Rabanne",
    gender: "fem",
    brandType: "clasica",
    tags: ["gourmand", "vainilla", "salado", "floral", "dulce", "cita", "noche", "verano", "otono", "dulce", "alta", "seductor", "elegante", "conocido"],
  },
  {
    id: "flowerbomb",
    name: "Flowerbomb",
    brand: "Viktor & Rolf",
    gender: "fem",
    brandType: "clasica",
    tags: ["floral", "gourmand", "dulce", "cita", "noche", "primavera", "otono", "dulce", "alta", "seductor", "elegante", "conocido"],
  },
  {
    id: "bonbon",
    name: "Bonbon",
    brand: "Viktor & Rolf",
    gender: "fem",
    brandType: "clasica",
    tags: ["gourmand", "frutal", "caramelo", "dulce", "fiesta", "cita", "invierno", "otono", "muy-dulce", "alta", "cercano", "seductor", "conocido"],
  },
  {
    id: "alien",
    name: "Alien",
    brand: "Thierry Mugler",
    gender: "fem",
    brandType: "clasica",
    tags: ["floral", "amaderada", "ambar", "dulce", "noche", "cita", "otono", "invierno", "dulce", "bestia", "misterio", "lujo", "conocido"],
  },
  {
    id: "angel",
    name: "Angel",
    brand: "Thierry Mugler",
    gender: "fem",
    brandType: "clasica",
    tags: ["gourmand", "chocolate", "frutal", "dulce", "noche", "invierno", "otono", "muy-dulce", "bestia", "original", "misterio", "diferente"],
  },
  {
    id: "bright-crystal",
    name: "Bright Crystal",
    brand: "Versace",
    gender: "fem",
    brandType: "clasica",
    tags: ["floral", "frutal", "fresca", "casual", "trabajo", "primavera", "verano", "ligero-dulce", "moderada", "cercano", "versatil", "popular"],
  },
  {
    id: "burberry-her",
    name: "Burberry Her",
    brand: "Burberry",
    gender: "fem",
    brandType: "clasica",
    tags: ["frutal", "gourmand", "dulce", "casual", "cita", "otono", "invierno", "dulce", "alta", "cercano", "seductor", "conocido"],
  },
  {
    id: "cloud",
    name: "Cloud",
    brand: "Ariana Grande",
    gender: "fem",
    brandType: "clasica",
    tags: ["gourmand", "vainilla", "frutal", "dulce", "casual", "cita", "invierno", "primavera", "muy-dulce", "moderada", "cercano", "versatil", "popular"],
  },
  {
    id: "twilly",
    name: "Twilly d'Hermès",
    brand: "Hermès",
    gender: "fem",
    brandType: "clasica",
    tags: ["floral", "especiada", "jengibre", "cita", "casual", "primavera", "otono", "ligero-dulce", "moderada", "original", "elegante", "diferente"],
  },
  {
    id: "gucci-bloom",
    name: "Gucci Bloom",
    brand: "Gucci",
    gender: "fem",
    brandType: "clasica",
    tags: ["floral", "blanco", "trabajo", "cita", "primavera", "verano", "ligero-dulce", "moderada", "elegante", "lujo", "conocido"],
  },

  // ---------- FEMENINOS ÁRABES ----------
  {
    id: "yara",
    name: "Yara",
    brand: "Lattafa",
    gender: "fem",
    brandType: "arabe",
    tags: ["gourmand", "frutal", "floral", "dulce", "casual", "cita", "invierno", "primavera", "muy-dulce", "alta", "cercano", "seductor", "diferente"],
  },
  {
    id: "mayar",
    name: "Mayar",
    brand: "Lattafa",
    gender: "fem",
    brandType: "arabe",
    tags: ["floral", "frutal", "dulce", "fiesta", "cita", "primavera", "verano", "dulce", "alta", "aventurero", "seductor", "diferente"],
  },
  {
    id: "fakhar-rose",
    name: "Fakhar Rosé",
    brand: "Lattafa",
    gender: "fem",
    brandType: "arabe",
    tags: ["floral", "frutal", "rosa", "dulce", "cita", "noche", "otono", "primavera", "dulce", "alta", "elegante", "seductor", "diferente"],
  },
  {
    id: "opulent-musk",
    name: "Opulent Musk",
    brand: "Lattafa",
    gender: "fem",
    brandType: "arabe",
    tags: ["gourmand", "almizcle", "dulce", "casual", "cita", "invierno", "otono", "dulce", "moderada", "cercano", "calido", "diferente"],
  },
  {
    id: "badee-amethyst",
    name: "Bade'e Al Oud Amethyst",
    brand: "Lattafa",
    gender: "unisex",
    brandType: "arabe",
    tags: ["frutal", "oud", "amaderada", "dulce", "noche", "cita", "otono", "invierno", "dulce", "bestia", "lujo", "misterio", "diferente"],
  },
  {
    id: "noble-blush",
    name: "Noble Blush",
    brand: "Lattafa",
    gender: "fem",
    brandType: "arabe",
    tags: ["floral", "frutal", "lichi", "dulce", "cita", "primavera", "verano", "dulce", "moderada", "cercano", "elegante", "diferente"],
  },

  // ---------- FRESCOS / VERSÁTILES ADICIONALES ----------
  {
    id: "light-blue-dg",
    name: "Light Blue",
    brand: "Dolce & Gabbana",
    gender: "unisex",
    brandType: "clasica",
    tags: ["citrica", "fresca", "frutal", "casual", "trabajo", "verano", "primavera", "nada-dulce", "moderada", "fresco", "versatil", "popular"],
  },
  {
    id: "cool-water",
    name: "Cool Water",
    brand: "Davidoff",
    gender: "masc",
    brandType: "clasica",
    tags: ["acuatica", "fresca", "aromatica", "casual", "trabajo", "verano", "primavera", "nada-dulce", "moderada", "fresco", "versatil", "popular"],
  },
  {
    id: "polo-blue",
    name: "Polo Blue",
    brand: "Ralph Lauren",
    gender: "masc",
    brandType: "clasica",
    tags: ["acuatica", "fresca", "aromatica", "casual", "trabajo", "verano", "primavera", "nada-dulce", "moderada", "fresco", "versatil", "cercano", "popular"],
  },
  {
    id: "leau-issey",
    name: "L'Eau d'Issey",
    brand: "Issey Miyake",
    gender: "masc",
    brandType: "clasica",
    tags: ["acuatica", "fresca", "citrica", "trabajo", "casual", "verano", "primavera", "nada-dulce", "moderada", "fresco", "elegante", "conocido"],
  },
  {
    id: "allure-sport",
    name: "Allure Homme Sport",
    brand: "Chanel",
    gender: "masc",
    brandType: "clasica",
    tags: ["citrica", "amaderada", "fresca", "trabajo", "casual", "cita", "verano", "primavera", "nada-dulce", "moderada", "elegante", "versatil", "lujo", "conocido"],
  },
]
